"""The release rehearsal: the release's own build, before a tag, publishing nothing.

``.github/workflows/rehearsal.yml`` is generated from the
``release.yml`` dist writes, so the rehearsal runs the same commands,
versions, runners and matrix. The transformation is small and strict: it
keeps the four build jobs (plan, the five archives, the wheels, the global
job), drops every job that hosts or publishes, strips the attestation steps
and every write permission and secret, and refuses any structure it does not
know (a dist upgrade that changes a job, a condition or a step stops here
until this file learns it).

Subcommands:

- ``generate [--check]``: write the rehearsal workflow, or fail when the
  checked-in copy differs from what ``release.yml`` produces (gatecheck.yml);
- ``impact --base SHA --head SHA``: whether the change touches what the
  release builds (``run=true|false`` to ``$GITHUB_OUTPUT``);
- ``assets --dir D --plan P``: every artifact the plan names, the four wheels
  with their ``.sha256``, every checksum, the payload's ``VERSION`` and, with
  ``--golden``, the Linux binary validating the golden fixture;
- ``verdict``: the required check. No impact passes as dispensed; with
  impact, every build job and the assets job must have succeeded: a failure,
  a cancellation or a skipped build fails it.

    python tool/tasks/rehearsal.py generate --check
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import os
import re
import subprocess
import sys
import tarfile
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RELEASE = ROOT / ".github" / "workflows" / "release.yml"
REHEARSAL = ROOT / ".github" / "workflows" / "rehearsal.yml"

KEEP = ("plan", "build-local-artifacts", "custom-wheelmake", "build-global-artifacts")
DROP = (
    "host",
    "publish-homebrew-formula",
    "publish-npm",
    "custom-rustready",
    "custom-pypiready",
    "announce",
    "custom-setuptest",
)
PLAN_RUN = (
    "dist ${{ (!github.event.pull_request && format('host --steps=create --tag={0}', "
    "github.ref_name)) || 'plan' }} --output-format=json > plan-dist-manifest.json"
)
LOCAL_IF = (
    "${{ fromJson(needs.plan.outputs.val).ci.github.artifacts_matrix.include != null && "
    "(needs.plan.outputs.publishing == 'true' || "
    "fromJson(needs.plan.outputs.val).ci.github.pr_run_mode == 'upload') }}"
)
WHEELS_IF = (
    "${{ needs.plan.outputs.publishing == 'true' || "
    "fromJson(needs.plan.outputs.val).ci.github.pr_run_mode == 'upload' }}"
)
BUILD_PERMS = {"attestations": "write", "contents": "read", "id-token": "write"}
READ = {"contents": "read"}
REQUIRED = ("plan", "build-local-artifacts", "custom-wheelmake", "build-global-artifacts")
HEADER = (
    "# GENERATED by tool/tasks/rehearsal.py from release.yml; do not edit.\n"
    "# the release's build jobs on a pull request or a push to main, publishing\n"
    "# nothing: `python tool/tasks/rehearsal.py generate` after `dist generate`.\n"
)


class Refused(Exception):
    pass


def _expect(cond: bool, msg: str) -> None:
    if not cond:
        raise Refused(f"release.yml: {msg}; teach tool/tasks/rehearsal.py the new shape")


def _plan_job(job: dict) -> dict:
    _expect(set(job.get("outputs", {})) == {"val", "tag", "tag-flag", "publishing"}, "plan outputs")
    _expect("needs" not in job and "if" not in job, "plan gained a condition")
    runs = [s for s in job["steps"] if s.get("id") == "plan"]
    _expect(len(runs) == 1 and runs[0]["run"].splitlines()[0] == PLAN_RUN, "the plan command")
    version = {
        "id": "version",
        "name": "the version a tag would carry",
        "run": 'echo "tag-flag=--tag=v$(python3 -c \'import sys; sys.path.insert(0, "tool/tasks");'
        " import embedpack as s; print(s.workspace_version())')\""
        ' >> "$GITHUB_OUTPUT"',
    }
    steps = []
    for step in job["steps"]:
        if step is runs[0]:
            steps.append(version)
            lines = step["run"].splitlines()
            lines[0] = (
                "dist plan ${{ steps.version.outputs.tag-flag }} --output-format=json"
                " > plan-dist-manifest.json"
            )
            step = {**step, "run": "\n".join(lines) + "\n"}
        steps.append(step)
    outputs = {
        "val": job["outputs"]["val"],
        "tag-flag": "${{ steps.version.outputs.tag-flag }}",
        "publishing": "false",
    }
    rest = {k: v for k, v in job.items() if k not in ("outputs", "steps")}
    return {
        "needs": ["impact"],
        "if": "needs.impact.outputs.run == 'true'",
        **rest,
        "outputs": outputs,
        "steps": steps,
    }


def _local_job(job: dict) -> dict:
    _expect(job.get("if") == LOCAL_IF, "the build-local-artifacts condition")
    _expect(job.get("permissions") == BUILD_PERMS, "the build-local-artifacts permissions")
    attest = [s for s in job["steps"] if str(s.get("uses", "")).startswith("actions/attest@")]
    _expect(len(attest) == 1, "one attest step in build-local-artifacts")
    steps = [s for s in job["steps"] if s is not attest[0]]
    cond = "${{ fromJson(needs.plan.outputs.val).ci.github.artifacts_matrix.include != null }}"
    return {**job, "if": cond, "permissions": READ, "steps": steps}


def _wheels_job(job: dict) -> dict:
    _expect(job.get("if") == WHEELS_IF, "the custom-wheelmake condition")
    _expect(job.get("uses") == "./.github/workflows/wheelmake.yml", "the wheels workflow")
    _expect(
        job.get("permissions") == BUILD_PERMS and job.get("secrets") == "inherit",
        "the custom-wheelmake permissions",
    )
    out = {k: v for k, v in job.items() if k not in ("if", "secrets", "permissions")}
    return {**out, "permissions": READ}


def _global_job(job: dict) -> dict:
    _expect("if" not in job and "permissions" not in job, "build-global-artifacts gained a gate")
    return job


def transform(release: dict) -> dict:
    """The rehearsal workflow for a parsed release.yml, or Refused."""
    top = set(release) - {True}
    _expect(top == {"name", "permissions", "jobs"} and True in release, f"top-level keys {top}")
    jobs = release["jobs"]
    unknown, missing = set(jobs) - set(KEEP + DROP), set(KEEP + DROP) - set(jobs)
    _expect(
        not unknown and not missing, f"jobs unknown {sorted(unknown)} missing {sorted(missing)}"
    )
    kept = {
        "plan": _plan_job(jobs["plan"]),
        "build-local-artifacts": _local_job(jobs["build-local-artifacts"]),
        "custom-wheelmake": _wheels_job(jobs["custom-wheelmake"]),
        "build-global-artifacts": _global_job(jobs["build-global-artifacts"]),
    }
    # every mention of the secrets context must be the run's own token: this
    # refuses secrets.X, secrets['X'] and toJSON(secrets) alike.
    text = json.dumps(kept)
    reads = [m.group(0) for m in re.finditer(r"\bsecrets\b\S{0,24}", text)]
    # the token name must end there: secrets.GITHUB_TOKEN_EXTRA is another secret.
    own = re.compile(r"secrets\.GITHUB_TOKEN(?![A-Za-z0-9_-])")
    others = sorted({r for r in reads if not own.match(r)})
    _expect(not others, f"a kept job reads secrets {others}")
    return {
        "name": "Release rehearsal",
        "on": {"pull_request": None, "push": {"branches": ["main"]}, "workflow_dispatch": None},
        "permissions": READ,
        "concurrency": {"group": "rehearsal-${{ github.ref }}", "cancel-in-progress": True},
        "jobs": {
            "impact": _impact_job(),
            **kept,
            "assets": _assets_job(),
            "rehearsal": _verdict_job(),
        },
    }


def _pinned(action: str) -> str:
    """``action@<commit>`` from the commits dist pins in release.yml
    (``github-action-commits`` in Cargo.toml), so the jobs added here run the
    same code as the ones kept."""
    import tomllib

    dist = tomllib.loads((ROOT / "Cargo.toml").read_text(encoding="utf-8"))
    pins = dist["workspace"]["metadata"]["dist"].get("github-action-commits", {})
    if action not in pins:
        raise Refused(f"Cargo.toml: github-action-commits pins no commit for {action}")
    return f"{action}@{pins[action]}"


def _impact_job() -> dict:
    run = (
        'case "$EVENT" in\n'
        "  workflow_dispatch) echo 'run=true' >> \"$GITHUB_OUTPUT\" ;;\n"
        "  pull_request) python3 tool/tasks/rehearsal.py impact \\\n"
        '    --base "$PR_BASE" --head "$PR_HEAD" ;;\n'
        "  *) python3 tool/tasks/rehearsal.py impact \\\n"
        '    --base "$BEFORE" --head "$GITHUB_SHA" ;;\n'
        "esac\n"
    )
    env = {
        "EVENT": "${{ github.event_name }}",
        "PR_BASE": "${{ github.event.pull_request.base.sha }}",
        "PR_HEAD": "${{ github.event.pull_request.head.sha }}",
        "BEFORE": "${{ github.event.before }}",
    }
    return {
        "name": "does this change touch what the release builds",
        "runs-on": "ubuntu-24.04",
        "outputs": {"run": "${{ steps.impact.outputs.run }}"},
        "steps": [
            {
                "uses": _pinned("actions/checkout"),
                "with": {"fetch-depth": 0, "persist-credentials": False},
            },
            {"id": "impact", "env": env, "run": run},
        ],
    }


def _assets_job() -> dict:
    run = (
        "printf '%s' \"$PLAN\" > plan.json\n"
        "python3 tool/tasks/rehearsal.py assets --dir dist --plan plan.json \\\n"
        "  --golden rust/format/tests/fixtures/golden_v1_minimal.urna\n"
    )
    return {
        "name": "the artifacts a release would upload",
        "needs": ["plan", "build-global-artifacts"],
        "runs-on": "ubuntu-24.04",
        "steps": [
            {"uses": _pinned("actions/checkout"), "with": {"persist-credentials": False}},
            {
                "uses": _pinned("actions/download-artifact"),
                "with": {"pattern": "artifacts-*", "path": "dist", "merge-multiple": True},
            },
            {"env": {"PLAN": "${{ needs.plan.outputs.val }}"}, "run": run},
        ],
    }


def _verdict_job() -> dict:
    return {
        "name": "rehearsal",
        "needs": ["impact", *REQUIRED, "assets"],
        "if": "always()",
        "runs-on": "ubuntu-24.04",
        "steps": [
            {"uses": _pinned("actions/checkout"), "with": {"persist-credentials": False}},
            {
                "env": {"NEEDS": "${{ toJSON(needs) }}"},
                "run": "python3 tool/tasks/rehearsal.py verdict",
            },
        ],
    }


def _dump(workflow: dict) -> str:
    import yaml

    class Dumper(yaml.SafeDumper):
        def ignore_aliases(self, data):  # each block written out, no &anchors
            return True

    def text(dumper, value):
        style = "|" if "\n" in value else None
        return dumper.represent_scalar("tag:yaml.org,2002:str", value, style=style)

    Dumper.add_representer(str, text)
    return HEADER + yaml.dump(workflow, Dumper=Dumper, sort_keys=False, width=1000)


def generate(check: bool) -> int:
    import yaml

    text = _dump(transform(yaml.safe_load(RELEASE.read_text(encoding="utf-8"))))
    if check:
        if not REHEARSAL.is_file() or REHEARSAL.read_text(encoding="utf-8") != text:
            print("rehearsal: rehearsal.yml is stale; run generate", file=sys.stderr)
            return 1
        print("rehearsal: rehearsal.yml matches release.yml")
        return 0
    REHEARSAL.write_text(text, encoding="utf-8")
    print(f"rehearsal: wrote {REHEARSAL.relative_to(ROOT)}")
    return 0


def _load(name: str):
    spec = importlib.util.spec_from_file_location(name, ROOT / "tool" / "tasks" / f"{name}.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def release_inputs() -> tuple[set[str], tuple[str, ...], str]:
    """(exact paths, path prefixes, the potion table's prefix) whose change
    reaches a release artifact."""
    payload, wheel = _load("embedpack"), _load("wheelprep")
    exact = {f"rust/bridge/python/urna/{n}" for n in payload.MODULES}
    exact |= {src.relative_to(ROOT).as_posix() for src, _ in wheel.COPIES}
    exact |= {
        "Cargo.toml",
        "Cargo.lock",
        "README.md",
        "LICENSE",
        ".github/buildprep.yml",
        "tool/tasks/getpotion.sh",
        "tool/tasks/embedpack.py",
        "tool/tasks/wheelprep.py",
        "tool/tasks/rehearsal.py",
        "tool/tasks/preflight.py",
        ".github/workflows/release.yml",
        ".github/workflows/rehearsal.yml",
        ".github/workflows/wheelmake.yml",
        ".github/workflows/tagverify.yml",
    }
    # the potion table, shipped by the payload and the wheel alike.
    model = wheel.MODEL_SRC.relative_to(ROOT).as_posix() + "/"
    return exact, ("rust/", "pkgs/wheel/"), model


# under rust/ but no release artifact builds it: rust/ingest is its own
# workspace, excluded by the root manifest, and of the urna package the
# release ships only the modules in the exact set and the potion table.
OUTSIDE_RELEASE = ("rust/ingest/", "rust/bridge/python/")


def touches_release(paths: list[str]) -> list[str]:
    exact, prefixes, model = release_inputs()
    return [
        p
        for p in paths
        if p in exact
        or p.startswith(model)
        or (p.startswith(prefixes) and not p.startswith(OUTSIDE_RELEASE))
    ]


def changed(base: str, head: str) -> list[str] | None:
    """The paths a change touched, or None when the base is unknown (run)."""
    if not base or set(base) == {"0"}:
        return None
    diff = subprocess.run(
        ["git", "-C", str(ROOT), "diff", "--name-only", f"{base}...{head}"],
        capture_output=True,
        text=True,
    )
    return diff.stdout.split() if diff.returncode == 0 else None


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _sidecar_ok(path: Path) -> bool:
    side = path.with_name(path.name + ".sha256")
    if not side.is_file():
        return False
    digest, _, name = side.read_text(encoding="utf-8").strip().partition(" ")
    return name.lstrip("*") == path.name and digest == _sha256(path)


def check_assets(directory: Path, plan: dict, version: str) -> list[str]:
    errors = [
        f"missing {name}" for name in sorted(plan["artifacts"]) if not (directory / name).is_file()
    ]
    wheels = sorted(directory.glob(f"urna-{version}-cp312-abi3-*.whl"))
    if len(wheels) != 4:
        errors.append(f"{len(wheels)} urna {version} wheels, expected 4")
    checked = [
        *wheels,
        *(
            directory / n
            for n, a in plan["artifacts"].items()
            if (directory / f"{n}.sha256").is_file() and not n.endswith(".sha256")
        ),
    ]
    errors += [f"{p.name} does not match its .sha256" for p in checked if not _sidecar_ok(p)]
    unified = directory / "sha256.sum"
    if unified.is_file():
        listed = set()
        # dist's file ends in a blank line.
        for line in filter(str.strip, unified.read_text(encoding="utf-8").splitlines()):
            digest, _, name = line.partition(" ")
            name = name.strip().lstrip("*")
            listed.add(name)
            target = directory / name
            if not target.is_file() or _sha256(target) != digest:
                errors.append(f"sha256.sum: {name} does not match")
        # what dist indexes there: the archives and the packaged installers.
        covered = {
            n
            for n, a in plan["artifacts"].items()
            if a.get("kind") == "executable-zip"
            or (a.get("kind") == "installer" and n.endswith((".tar.gz", ".zip")))
        }
        errors += [f"sha256.sum lacks {n}" for n in sorted(covered - listed)]
    payload = directory / "urna-embedder-payload.tar.gz"
    if payload.is_file():
        with tarfile.open(payload) as tar:
            member = tar.extractfile("urna/VERSION")
            stamped = member.read().decode().strip() if member else None
        if stamped != version:
            errors.append(f"payload VERSION is {stamped!r}, not {version!r}")
    return errors


def check_binary(directory: Path, target: str, golden: Path, version: str) -> list[str]:
    # the exact archive names, never a glob: `urna-<target>.tar.*` also
    # matches the archive's .sha256, which sorts first on the runner.
    names = (f"urna-{target}.tar.xz", f"urna-{target}.tar.gz")
    archive = next((directory / n for n in names if (directory / n).is_file()), None)
    if archive is None:
        return [f"no urna-{target} archive"]
    with tempfile.TemporaryDirectory() as tmp, tarfile.open(archive) as tar:
        tar.extractall(tmp, filter="data")
        exe = next((p for p in Path(tmp).rglob("urna") if p.is_file()), None)
        if exe is None:
            return [f"{archive.name} has no urna binary"]
        exe.chmod(0o755)
        shown = subprocess.run([str(exe), "--version"], capture_output=True, text=True)
        valid = subprocess.run([str(exe), "validate", str(golden)], capture_output=True, text=True)
    errors = []
    if shown.returncode != 0 or shown.stdout.split() != ["urna", version]:
        said = f"{shown.stdout.strip()!r} (exit {shown.returncode})"
        errors.append(f"{archive.name}: --version says {said}, not 'urna {version}'")
    if valid.returncode != 0:
        why = valid.stderr.strip()
        errors.append(f"{archive.name}: validate {golden.name} exited {valid.returncode}: {why}")
    return errors


def verdict(needs: dict) -> tuple[bool, str]:
    impact = needs.get("impact", {})
    if impact.get("result") != "success":
        return False, f"the impact job ended {impact.get('result')!r}"
    run = (impact.get("outputs") or {}).get("run")
    if run == "false":
        return True, "no release input changed: rehearsal dispensed"
    if run != "true":
        return False, f"the impact job gave run={run!r}, neither 'true' nor 'false'"
    bad = {j: needs.get(j, {}).get("result") for j in (*REQUIRED, "assets")}
    bad = {j: r for j, r in bad.items() if r != "success"}
    if bad:
        return False, "rehearsal needed and not passed: " + ", ".join(
            f"{j} {r}" for j, r in bad.items()
        )
    return True, "every release build and the artifact checks passed"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("generate").add_argument("--check", action="store_true")
    imp = sub.add_parser("impact")
    imp.add_argument("--base", default="")
    imp.add_argument("--head", default="HEAD")
    assets = sub.add_parser("assets")
    assets.add_argument("--dir", type=Path, required=True)
    assets.add_argument("--plan", type=Path, required=True)
    assets.add_argument("--golden", type=Path)
    assets.add_argument("--target", default="x86_64-unknown-linux-musl")
    sub.add_parser("verdict")
    args = parser.parse_args(argv)
    try:
        if args.cmd == "generate":
            return generate(args.check)
    except Refused as err:
        print(f"rehearsal: {err}", file=sys.stderr)
        return 1
    if args.cmd == "impact":
        paths = changed(args.base, args.head)
        hits = ["(base unknown)"] if paths is None else touches_release(paths)
        print(
            "rehearsal: "
            + (f"release inputs changed: {hits}" if hits else "no release input changed")
        )
        if output := os.environ.get("GITHUB_OUTPUT"):
            with open(output, "a", encoding="utf-8") as fh:
                fh.write(f"run={'true' if hits else 'false'}\n")
        return 0
    if args.cmd == "verdict":
        ok, why = verdict(json.loads(os.environ.get("NEEDS", "{}")))
        print(f"rehearsal: {why}", file=sys.stdout if ok else sys.stderr)
        return 0 if ok else 1
    plan = json.loads(args.plan.read_text(encoding="utf-8"))
    version = _load("embedpack").workspace_version()
    errors = check_assets(args.dir, plan, version)
    if args.golden:
        errors += check_binary(args.dir, args.target, args.golden, version)
    for error in errors:
        print(f"rehearsal: {error}", file=sys.stderr)
    print(f"rehearsal: assets {'ok' if not errors else 'refused'} for {version}")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
